Подключает графику
htmlacademy-htmlcss/2297761-sedona-36 pull request #3
Opened 2023-01-31 17:11 UTC by FrauFri

2023-01-31 22:27 UTC, baronin requested changes
Давай, все картинки называть с маленьких букв и без пробелов, это нам сразу даст представление, что за картинка, так как index-background (1) сложно представить или photo-1. Нам нужно облегчить работу другому разработчику, что бы он по имени мог быстрей найти ту картинку которая ему понадобится![image](https://user-images.githubusercontent.com/20131942/215896899-f3f79409-0518-445c-830a-1568bcf02518.png)

2023-01-31 22:27 UTC, baronin commented on index.html
> +    <style>
Зачем это добавлено ?

2023-01-31 22:27 UTC, baronin commented on index.html
> +        <img class="logo" src="logo.svg" width="140" height="70" alt="Логотип города Седона">
src="logo.svg"  - говорит о том что нужно в корне файла найти картинку logo.svg, но у нас там ничего нет, все картинки находятся в папке images

Интересные  статьи 
https://up.htmlacademy.ru/htmlcss/36/module/3/item/9
https://htmlacademy.ru/blog/html/links

Хороший пример к ДЗ
![image](https://user-images.githubusercontent.com/20131942/215895637-39603f9e-9bef-4ebf-90ce-14579c6f9419.png)

2023-01-31 22:27 UTC, baronin commented on index.html
> +              <img src="search.svg" width="44" height="64" alt="Поиск">
попробуй src="images/search.svg"

2023-01-31 22:27 UTC, baronin commented on index.html
> +      <img class="hero-title" src="sedona.png" width="456.7" height="204.91"
Обычно(почти всегда) мы не ставим дроби, всегда округляем,` width="457" height="205"`

2023-01-31 22:27 UTC, baronin commented on index.html
> +            <div class="rectangle-125-1"></div>
Не понятно что значит `rectangle-125`, мы должны писать код так, что бы другому человеку было понятно, за что отвечает тот или иной класс

2023-01-31 22:27 UTC, baronin commented on index.html
> +            <div class="rectangle-125"></div>
Делаю пометку тут

2023-01-31 22:27 UTC, baronin commented on index.html
> +            <div class="rectangle-125"></div>
И тут

2023-02-07 07:26 UTC, baronin requested changes
Эту картинку нужно удалить, а если тебе нужен был фон, то скачай только фон и подпиши subscribe-background

2023-02-07 07:26 UTC, baronin commented on index.html
> +          <a class="navigation-link" href="main.html">Главная</a>
у нас главная страница, это index.html, но мы и так на ней, по этому убери `href="main.html"`

2023-02-07 07:26 UTC, baronin commented on index.html
> +          <a class="navigation-link " href="catalog.html">Гостиницы</a>
опечатка, лишний пробел `"navigation-link "`

2023-02-07 07:26 UTC, baronin commented on index.html
> +      <h2 class="main-description">Седона — небольшой городок в Аризоне,
У тебя секция названа main-description, а это заголовок, нам нужно указать другому разработчику что это класс для заголовка `main-description-title`

2023-02-07 07:26 UTC, baronin commented on index.html
> +      <p class="main-description-1">Рассмотрим причины, по которым Седона круче, чем Гранд-Каньон!</p>
тут описание, так как description занято возьмем другое слово definition "main-description-definition"

2023-02-07 07:26 UTC, baronin commented on index.html
> +        <li class="advantages-item-2">
Нам подходит класс advantages-item, давай оставим его advantages-item вместо advantages-item-2, и ниже так же , нужно везде убрать -1, -4, -5 - это нам не очем не говорит, человек не поймет что это значит

2023-02-07 07:26 UTC, baronin commented on index.html
> +    <section class="main-description">
Выше была секция main-description, это уже совсем другой блок, нужно переименовать

2023-02-07 07:26 UTC, baronin commented on index.html
> +        <li class="advice-item-2">
так же с -2, -3 и т.д , поудалять

2023-02-07 07:26 UTC, baronin commented on index.html
> +        <button class="submit" type="submit">
секция называется notification, кнопку давай назовем `notification-submit` - другой разработчик прочитает, и поймет что это кнопка сабмит относится к секции notification

2023-02-07 07:26 UTC, baronin commented on index.html
> +            <img class="button-vk" src="images/vk.svg" width="24" height="14" alt="лого вк">
это не кнопка button-vk, тут картинка, лучше назвать footer-social-img

2023-02-07 07:26 UTC, baronin commented on index.html
> +          <a class="button-vk" href="https://vk.com/htmlacademy">
лучше назвать footer-social-link, так как это ссылка, а уточнение что это вк просто дабавим в конце еще один класс footer-social-link-vk

с другими ссоциальными иконками так же по аналогии переделать нужно

2023-02-07 07:26 UTC, baronin commented on styles/styles.css
> +  src: url("fonts/pt-sans-regular.woff2");
1. у тебя в проекте на такого шрифта `pt-sans-regular` , так же можно открывать консоль, и там смотреть ошибки
<img width="790" alt="image" src="https://user-images.githubusercontent.com/20131942/217174681-65a819da-435f-4779-b684-5e83db88bede.png">

<img width="248" alt="image" src="https://user-images.githubusercontent.com/20131942/217174447-290752fa-5fc1-471b-829d-f0d35fde3784.png">

2. точка с запятой лишняя , src: url("fonts/pt-sans-regular.woff2")format ("woff2");
Если пример был от сюда 
https://htmlacademy.ru/blog/html/fonts-loading
<img width="878" alt="image" src="https://user-images.githubusercontent.com/20131942/217174003-d4baf09c-3277-49e1-aaed-2401373856cc.png">

Ниже так же нужно поправить

2023-02-07 07:26 UTC, baronin commented on styles/styles.css
> +.main-description-1 {
не забудь поудалять стили которые не исользуем, но точно можно будет удалить все то, гды было написано в классах -1, -2, -3

2023-02-07 07:26 UTC, baronin commented on styles/styles.css
> +input {
мы не задаем стили для тегов, есть исключения
https://up.htmlacademy.ru/htmlcss/33/criteries#CSS-02

2023-02-07 07:26 UTC, baronin commented on styles/styles.css
> +footer {
так же и тут, мы не стилим теги

2023-02-07 07:26 UTC, baronin commented on styles/styles.css
> +  color: black;
давай использовать на проекте везде hex, лучше вот так укажи #000000

2023-02-07 17:29 UTC, FrauFri commented on index.html
> +        <li class="advantages-item-2">
Если здесь убрать нумерацию, не будет разницы в фонах этих элементов, может я пропишу вместо advantages-item-2 что-то с указанием например фото или фона? advantage-item-cityview, advantage-item-light, advantage-item-dark.

2023-02-08 07:51 UTC, baronin commented on index.html
> +            <img class="button-vk" src="images/vk.svg" width="24" height="14" alt="лого вк">
Не исправлено

2023-02-08 07:58 UTC, baronin commented on index.html
> +    <section class="main-description">
Не исправлено

2023-02-08 07:58 UTC, baronin commented on index.html
> +        <li class="advantages-item-dark">
Нужно не заменить класс, а добавить к advantages-item и advantages-item-dark
`<li class="advantages-item advantages-item-dark">`, так же и в других лишках

2023-02-08 07:58 UTC, baronin commented on index.html
> +          <img class="advantages-image-1" src="images/advantages-image-1.jpg" width="800" height="384"
advantages-image-1 - нам не очем не говорит, давай избегать 1, 2 ,3 так как нет понимания что это значит, 
Тут просто оставь класс advantages-image, а картинку назови advantages-image-view-sedona, другую лишку так же исправь

2023-02-08 07:58 UTC, baronin commented on index.html
> +        <li class="advantages-item-2">
Обговорили

2023-02-08 08:30 UTC, baronin requested changes

2023-02-08 08:30 UTC, baronin commented on styles/styles.css
> +  src: url("fonts/pt-sans.woff2")
нету такого pt-sans.woff2 шрифта в папке fonts

2023-02-08 08:30 UTC, baronin commented on styles/styles.css
> +  src: url("fonts/pt-sans-italic.woff2")
и такой тоже у меня не отобразился

2023-02-08 08:30 UTC, baronin commented on styles/styles.css
> +  src: url("fonts/pt-sans-bold-italic.woff2")
+

2023-02-08 10:24 UTC, FrauFri commented on index.html
> +        <li class="advantages-item-dark">
добавила

2023-02-08 10:27 UTC, FrauFri commented on index.html
> +          <img class="advantages-image-1" src="images/advantages-image-1.jpg" width="800" height="384"
переименовала

2023-02-08 10:27 UTC, FrauFri commented on styles/styles.css
> +  color: black;
сделала

2023-02-08 10:30 UTC, FrauFri commented on styles/styles.css
> +  src: url("fonts/pt-sans.woff2")
исправила

2023-02-08 10:31 UTC, FrauFri commented on styles/styles.css
> +  src: url("fonts/pt-sans-italic.woff2")
удалила

2023-02-08 10:31 UTC, FrauFri commented on styles/styles.css
> +  src: url("fonts/pt-sans-bold-italic.woff2")
удалила

2023-02-10 13:50 UTC, baronin requested changes
Пройдись по цвету, размеру текста в  проекте
На макете цвет текста белый, но у нас сейчас он черный
![image](https://user-images.githubusercontent.com/20131942/218107685-a04585c7-3690-4b52-b237-468186e8c4eb.png)

Так же попробуй задать размер для placeholder'a как на макете
![image](https://user-images.githubusercontent.com/20131942/218107893-20f4a542-2b1e-4c3a-9f41-c6b73507d72d.png)

2023-02-15 08:20 UTC, merged