располагает элементы страниц по сетке
htmlacademy-htmlcss/2297761-sedona-36 pull request #4
Opened 2023-02-15 21:51 UTC by FrauFri

2023-02-16 20:59 UTC, baronin requested changes
- [x] на странице присутствует горизонтальный скролл
![image](https://user-images.githubusercontent.com/20131942/219483216-7249b6ca-3ad9-40ce-9446-ce86b60434e1.png)

- [x] не работает стики футер
![image](https://user-images.githubusercontent.com/20131942/219483447-082e9fc5-3914-415b-abfe-e57d2724ceaa.png)

- [x] Не отформатирован код
![image](https://user-images.githubusercontent.com/20131942/219483890-f8b7a486-c7f3-4e34-a8b9-57a51333e96c.png)

2023-02-16 20:59 UTC, baronin commented on catalog.html
> +          <ul class="hotel-card-list">
Нет стилей для этого блока

2023-02-16 20:59 UTC, baronin commented on catalog.html
> +              <img class="hotel-card-raiting" src="images/catalog/star.svg" width="18" height="17" alt="Звездочка">
похоже на список

2023-02-16 20:59 UTC, baronin commented on catalog.html
> +        <a class="navigation-logo" href="catalog.html">
Логотип всегда ведет на главную страницу

2023-02-16 20:59 UTC, baronin commented on catalog.html
> +              <img src="images/search.svg" width="44" height="64" alt="Поиск">
Не верно заданы размеры для картинки

2023-02-16 20:59 UTC, baronin commented on catalog.html
> +              <img src="images/like.svg" width="44" height="64" alt="Сердце">
Не верно заданы размеры для картинки

2023-02-16 20:59 UTC, baronin commented on styles/styles.css
>    padding: 96px 304px;
Таких больших падингов у проектов обычно не бывает, это редкий случай, там нужно решить с помощью центрирования блока и max-width

2023-02-24 20:41 UTC, FrauFri commented on catalog.html
> +        <a class="navigation-logo" href="catalog.html">
исправила

2023-02-24 20:41 UTC, FrauFri commented on catalog.html
> +              <img src="images/search.svg" width="44" height="64" alt="Поиск">
исправила

2023-02-24 20:42 UTC, FrauFri commented on catalog.html
> +              <img src="images/like.svg" width="44" height="64" alt="Сердце">
исправила

2023-02-24 20:45 UTC, FrauFri commented on styles/styles.css
>    padding: 96px 304px;
96px можно оставить (padding-top, padding-bottom)?

2023-02-24 20:45 UTC, FrauFri commented on catalog.html
> +          <ul class="hotel-card-list">
добавила

2023-02-24 21:34 UTC, FrauFri commented on catalog.html
> +              <img class="hotel-card-raiting" src="images/catalog/star.svg" width="18" height="17" alt="Звездочка">
здесь не очень понятно, какой список( Это части списка большого, нужно сделать подсписок каждой карточки? То есть у нас есть список карточек и у каждой карточки список с содержанием конкретной карточки?

2023-02-27 13:05 UTC, baronin requested changes

2023-02-27 13:05 UTC, baronin commented on catalog.html
> +      <main class="main-container">
Почему тут решила все удалить ?

2023-02-27 13:05 UTC, baronin commented on index.html
> +            <ul class="advantages-list">
Добавил еще два блока, и они должны перейти в низ, но этого не произошло, давай поправим перенаполнение 
![image](https://user-images.githubusercontent.com/20131942/221571116-4fa2e730-7b03-484e-9ed7-a623012c097f.png)

2023-02-27 14:11 UTC, FrauFri commented on index.html
> +            <ul class="advantages-list">
добавила в advantages-list flex-wrap: wrap
переносятся новые пункты вниз

2023-02-27 14:14 UTC, FrauFri commented on catalog.html
> +      <main class="main-container">
Всё на месте. возможно, отправила промежуточный вариант(( не внимательно проверяла

2023-02-28 11:04 UTC, baronin requested changes

2023-02-28 11:04 UTC, baronin commented on styles/styles.css
> +  padding-top: 96px;
Если бы у заголовка был отступ, то это внешний отступ(маргин), но тут он лишний
И падинг нужно задавать секции

2023-02-28 11:04 UTC, baronin commented on catalog.html
> +          <a class="navigation-logo" href="catalog.html">
Логотип всегда ведет на главную

2023-02-28 11:04 UTC, baronin commented on catalog.html
> +                  <button class="button-transporent" type="submit">Сбросить
Тут тип давай укажем reset
type="reset"

2023-02-28 11:04 UTC, baronin commented on catalog.html
> +                <img class="hotel-star-raiting" src="images/catalog/star.svg" width="18" height="17" alt="Звездочка">
Звезды давай сделаем списком

2023-02-28 15:08 UTC, FrauFri commented on styles/styles.css
> +  padding-top: 96px;
убрала отступ у заголовка, добавила отступы сверху и снизу у секции, убрала высоту.

2023-02-28 15:10 UTC, FrauFri commented on catalog.html
> +          <a class="navigation-logo" href="catalog.html">
поменяла путь логотипа и в каталоге, и на главной странице

2023-02-28 15:11 UTC, FrauFri commented on catalog.html
> +                  <button class="button-transporent" type="submit">Сбросить
указала reset

2023-02-28 15:18 UTC, FrauFri commented on catalog.html
> +                <img class="hotel-star-raiting" src="images/catalog/star.svg" width="18" height="17" alt="Звездочка">
обернула звезды в <ul class="star-list">

2023-03-02 06:37 UTC, baronin requested changes

2023-03-02 06:37 UTC, baronin commented on catalog.html
> +                  <ul class="star-list">
список сделан не верно, у ul должны быть айтемы
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul

2023-03-02 06:37 UTC, baronin commented on styles/styles.css
> +.notification-catalog
тут не понятно, должна быть комма поле .notification-catalog или случайно перенесла .notification-title-catalog ниже

2023-03-02 06:37 UTC, baronin commented on styles/styles.css
> +
лишний отступ

2023-03-02 07:22 UTC, FrauFri commented on catalog.html
> +                  <ul class="star-list">
дополнила

2023-03-02 07:22 UTC, FrauFri commented on styles/styles.css
> +.notification-catalog
удалила

2023-03-02 07:23 UTC, FrauFri commented on styles/styles.css
> +
удалила

2023-03-02 08:33 UTC, baronin approved these changes

2023-03-02 08:33 UTC, merged