Мелкие сетки на гридах
htmlacademy-htmlcss/2297761-sedona-36 pull request #5
Opened 2023-03-03 12:43 UTC by FrauFri

2023-03-04 12:49 UTC, baronin requested changes
Нужно удалить эти изображения с проекта
<img width="312" alt="image" src="https://user-images.githubusercontent.com/20131942/222902034-a81139c4-34a9-4f1e-a27c-501444ba7eb1.png">

Не выполнено задание: 
Масштабируйте картинки карточек товара с помощью object-fit.

2023-03-07 03:29 UTC, baronin requested changes

2023-03-07 03:29 UTC, baronin commented on styles/styles.css
> +  background-image: url("images/vk.svg");
В папке styles нет папки images, и второе, почему ты решила задать фоном социальные сети? у тебя инлайново прописаны картинки

<img width="490" alt="image" src="https://user-images.githubusercontent.com/20131942/223311232-a45e8a71-808f-4d10-a0f6-1e2609b007d8.png">

2023-03-07 06:04 UTC, FrauFri commented on styles/styles.css
> +  background-image: url("images/vk.svg");
удалила фоны в соцсетях, оставила img

2023-03-07 07:01 UTC, merged