оформляет декоративные элементы
htmlacademy-htmlcss/2297761-sedona-36 pull request #6
Opened 2023-03-10 00:00 UTC by FrauFri

2023-03-10 06:24 UTC, baronin requested changes
Нам нужно сделать header по макету, обрати внимание на логотип и как подсвечивается активная ссылка
<img width="639" alt="image" src="https://user-images.githubusercontent.com/20131942/224239166-a1c6a525-c1fc-4a54-b204-46cb04aec692.png">

2023-03-10 06:24 UTC, baronin commented on catalog.html
> +            <a class="navigation-link-list">Главная</a>
navigation-link-list - почему добавила list ? list - это список, а у нас тут ссылка, все было корректно

2023-03-10 06:24 UTC, baronin commented on catalog.html
> +                <svg class="button-vk" xmlns="http://www.w3.org/2000/svg" width="25" height="15" fill="none" viewBox="0 0 25 15">
у **svg** класс **button-vk**, но и у тега **а** класс **button-vk** ,  у них действительно одинаковые стили ? 
Но и еще давай лучше поменяем класс, что бы другому разработчику было понятно, что это за кнопки, у нас этот блок начинается с footer-social, вот давай покажем, что эти кнопки относятся к этому блоку

То что повторяется `footer-social-svg`, а где будут различия `footer-social-svg-vk`

2023-03-10 06:24 UTC, baronin commented on catalog.html
> +                <svg class="button-telegram" xmlns="http://www.w3.org/2000/svg" width="18" height="17" fill="none" viewBox="0 0 18 17">
- [ ] обратить внимание

2023-03-10 06:24 UTC, baronin commented on catalog.html
> +                <svg class="button-you" xmlns="http://www.w3.org/2000/svg" width="23" height="18" fill="none" viewBox="0 0 23 18">
- [ ] обратить внимание

2023-03-10 06:24 UTC, baronin commented on catalog.html
>                <a class="button-you" href="https://www.youtube.com/user/htmlacademyru">
- [ ] обратить внимание

2023-03-10 06:24 UTC, baronin commented on catalog.html
>                <a class="button-telegram" href="https://t.me/htmlacademy ">
- [ ] обратить внимание

2023-03-10 06:24 UTC, baronin commented on catalog.html
> +            <a class="phone" href="tel:+78121212">+7 (812) 812-12-12
тут повторяются классы, да и не совсем понятно к какой секции относится phone
но мы исправим на footer-phone-link

2023-03-10 06:24 UTC, baronin commented on catalog.html
> +          <div class="phone">
изменить класс на footer-phone-wrap

2023-03-10 06:24 UTC, baronin commented on index.html
> +                  <svg class="button-vk" xmlns="http://www.w3.org/2000/svg" width="25" height="15" fill="none" viewBox="0 0 25 15">
На странице каталог описал по названиям класса

2023-03-10 06:24 UTC, baronin commented on index.html
> +              <a class="phone" href="tel:+78121212">+7 (812) 812-12-12
Поменять класс, и в стилях не забудь изменить класс

2023-03-10 06:24 UTC, baronin commented on styles/styles.css
> +
о, супер что убрала с бади оверфлоу !

2023-03-10 06:24 UTC, baronin commented on styles/styles.css
>    flex: block;
тут не совсем понимаю, для чего это ?

2023-03-10 06:24 UTC, baronin commented on styles/styles.css
> +  content: "";
Что делает это свойство ?

2023-03-10 06:24 UTC, baronin commented on styles/styles.css
> +  fill: #68A2CA;
Свойства в разных классах дублируются, давай один класс зададим для них ? так мы сможем сэкономить 10 строчек кода

2023-03-10 06:24 UTC, baronin commented on styles/styles.css
> +.breadcrumbs-link:active {
Выше ты обьеденяла через запятую одинаковые свойства, можно и тут повторить
```
.breadcrumbs-link:disabled,
.breadcrumbs-link:active {
```

2023-03-10 06:24 UTC, baronin commented on styles/styles.css
> +  border: 1px solid #82B3D3;
То что дублируется лучше обьеденять, так мы экономим место в style.css
```
.pagination-link:hover,
.pagination-link:focus {
  background-color: #68A2CA;
  border: 1px solid #82B3D3;
}
```

2023-03-10 06:24 UTC, baronin commented on styles/styles.css
> +.button-button-blue:hover {
у нас есть кнопки с одинаковым стилями, давай может зададим класс универсальный ?
button-primary, если будет еще кнопка button-secondary

В этом классе .button-button-blue дублирование слова button, вводит в замешательство что это может быть

2023-03-10 07:54 UTC, FrauFri commented on catalog.html
> +                <svg class="button-vk" xmlns="http://www.w3.org/2000/svg" width="25" height="15" fill="none" viewBox="0 0 25 15">
заменила.

2023-03-10 07:55 UTC, FrauFri commented on catalog.html
> +                <svg class="button-telegram" xmlns="http://www.w3.org/2000/svg" width="18" height="17" fill="none" viewBox="0 0 18 17">
заменила

2023-03-10 07:56 UTC, FrauFri commented on catalog.html
> +                <svg class="button-you" xmlns="http://www.w3.org/2000/svg" width="23" height="18" fill="none" viewBox="0 0 23 18">
заменила

2023-03-10 07:56 UTC, FrauFri commented on catalog.html
>                <a class="button-you" href="https://www.youtube.com/user/htmlacademyru">
заменила

2023-03-10 07:57 UTC, FrauFri commented on catalog.html
>                <a class="button-telegram" href="https://t.me/htmlacademy ">
+

2023-03-10 07:59 UTC, FrauFri commented on catalog.html
> +            <a class="phone" href="tel:+78121212">+7 (812) 812-12-12
заменила

2023-03-10 08:01 UTC, FrauFri commented on catalog.html
> +          <div class="phone">
заменила

2023-03-10 08:01 UTC, FrauFri commented on index.html
> +                  <svg class="button-vk" xmlns="http://www.w3.org/2000/svg" width="25" height="15" fill="none" viewBox="0 0 25 15">
+

2023-03-10 08:02 UTC, FrauFri commented on index.html
> +              <a class="phone" href="tel:+78121212">+7 (812) 812-12-12
+

2023-03-10 09:01 UTC, FrauFri commented on styles/styles.css
> +
+

2023-03-10 09:01 UTC, FrauFri commented on styles/styles.css
>    flex: block;
удалила

2023-03-10 09:23 UTC, FrauFri commented on styles/styles.css
> +  fill: #68A2CA;
+

2023-03-10 09:40 UTC, FrauFri commented on styles/styles.css
> +.breadcrumbs-link:active {
+

2023-03-10 09:42 UTC, FrauFri commented on styles/styles.css
> +  border: 1px solid #82B3D3;
+

2023-03-10 10:13 UTC, FrauFri commented on styles/styles.css
> +.button-button-blue:hover {
сделано!

2023-03-10 10:17 UTC, FrauFri commented on catalog.html
> +            <a class="navigation-link-list">Главная</a>
заменила на navigation-link-item .Нужна разница с левым списком навигации (там нет подчеркивания)

2023-03-12 18:16 UTC, baronin commented on styles/styles.css
> +.breadcrumbs-link:active {
-

2023-03-12 19:47 UTC, baronin approved these changes

2023-03-13 19:49 UTC, merged